name: flutter_book
description: flutter_book
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  scoped_model: ^2.0.0
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  flutter_slidable: ^3.0.0
  intl: ^0.18.1
  image_picker: ^0.8.7+5
  flutter_calendar_carousel: ^2.4.2
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
